# Generated by Django 2.2.6 on 2019-11-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=10)),
                ('isbn', models.IntegerField()),
                ('document', models.FileField(upload_to='document')),
                ('published_date', models.DateField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
