# Generated by Django 2.2.6 on 2019-11-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(default=1, upload_to='document/image'),
            preserve_default=False,
        ),
    ]
